# raspi user zhkath
# todo: hier user eintragen
# raspi ansible_ssh_host=192.168.0.227


all:
  hosts:
    raspi:
      ansible_connection: ssh
      ansible_host: venusrulestheworld
      ansible_user: pi
      ansible_os_family: Debian
    # zhkath.rohberg.ch:
    #   ansible_connection: ssh
    #   ansible_host: "81.169.235.151"
    #   ansible_user: pi
    awstest.rohberg.ch:
      ansible_connection: ssh
      ansible_host: 18.196.193.209
      ansible_user: ubuntu
