---

# Medium configuration
# --------------------
#
# This is a good start for larger configurations.
# Just scale the client counts and cache/memory.
#
# This targets a medium server::
#
#     RAM: 2048MB
#     Cores: 2


# Things you MUST change
# ----------------------

admin_email: admins@plone.org

plone_initial_password: bubba

#muninnode_query_ips:
#    - ip.of.munin.monitor

# If you do not have a Munin monitor running, comment out the
# muninnode_query_ips and uncomment the line below:

install_muninnode: no


# Major settings
# --------------

# Plone 4.3.x, 5.0.x and 5.1.x are currently tested and working.
# Make sure this setting is quoted so that it's interpreted as a string.
plone_version: '5.1.4'

# 2 clients
plone_client_count: 2

# smallish
plone_zodb_cache_size: 15000

# and enforce that with a memory-monitor
plone_client_max_memory: 750MB

# Kim testing stuff below
plone_autorun_buildout: yes # doesn't seem to work
plone_always_run_buildout: yes

plone_site_id: Ploneconf2019

webserver_virtualhosts:
  - hostname: "{{ inventory_hostname }}"
    aliases:
      - default
    zodb_path: /Ploneconf2019

client_max_body_size: 6M

plone_sources:
  - "ploneconf2016.policy = git https://github.com/plone/ploneconf2016.policy.git"
  - "ploneconf2017.theme = git https://github.com/sneridagh/ploneconf2017.theme.git"
  - "collective.fbshare = git https://github.com/alecpm/collective.fbshare.git rev=86056e4ef74f536375bf8c7d538f1612d7a163d2"
  - "collective.relatedslider = git https://github.com/collective/collective.relatedslider.git"

plone_additional_eggs:
  - ploneconf2016.policy
  - ploneconf2017.theme
  - uwosh.pfg.d2c
  - collective.recaptcha

plone_additional_versions:
  - "Products.PythonField = 1.1.3"
  - "Products.TemplateFields = 1.2.5"
  - "chardet = 3.0.4"
  - "collective.recaptcha = 2.1.0"
  - "five.z2monitor = 0.2"
  - "idna = 2.6"
  - "pbr = 5.1.1"
  - "uwosh.pfg.d2c = 2.4.6"
  - "Products.PloneFormGen = 1.8.5"
  - "Products.QuickImporter = 0.2.2"
  - "Products.RedirectionTool = 1.4.1"
  - "Products.TALESField = 1.1.3"
  - "collective.addthis = 1.3.3"
  - "collective.pantry = 1.0a1"
  - "collective.recaptchacontactform = 1.0.0"
  - "norecaptcha = 0.3.0"
  - "plone.app.jquerytools = 1.9.5"
  - "plone.app.themingplugins = 1.0"
  - "plone.formwidget.recaptcha = 2.0.0"
  - "zc.monitor = 0.3.1"
  - "zc.ngi = 2.1.0"
  - "zc.z3monitor = 0.8.0"