---

- src: https://github.com/plone/ansible.plone_server.git
  version: 1.3.8
  name: plone.plone_server

- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: v1.5.0
  name: jnv.unattended-upgrades
